### ISSUE TITLE
Performance improvement - check file / directory operations' usages

### ISSUE THREAD

**Issue by PeterDSteinberg** [PSLmodels/OG-USA#318] opened 2017-10-13 15:27 UTC
For the portions of OG-USA that are run in in functions called by web frontend, review the usage of temporary / scratch / output directory and file handling to see if some can be avoided in some/all situations, e.g. this from execute.py.

```
dirs = [saved_moments_dir, ss_dir, tpi_dir]
    for _dir in dirs:
        try:
            print "making dir: ", _dir
            os.makedirs(_dir)
        except OSError as oe:
            pass
```

**Comment by hdoupe** [comment] 2017-10-13 15:31
@PeterDSteinberg In PR #316, I ran into some issues setting a specific path to an output directory for reform and baseline runs.  I made some changes that worked well enough to run the regression tests.  But, I would appreciate it if you could find some time to review them.  Maybe there's a better way to do this.

**Comment by jdebacker** [comment] 2018-05-25 17:45
Try a boolean to trigger saving pickle files (e.g, `save_data`).  If `False`, then don't have tax functions to disk.  Will need to refactor running/reading of tax function pickles to do this.  This boolean will have to work together with `run_micro`.  E.g., need to think about how `run_micro=False` and `save_data=False` would work.  Probably just don't want this combination of parameters to be allowed. 

Will restructure OG-USA to make OG-USA class.  This will not be saved to disk by default.

**Comment by rickecon** [comment] 2018-05-25 18:01
Wait. It seems like anyone running OG-USA locally would want these pickle file saved to disk by default, which allows them to skip a lengthy computation for subsequent runs. It seems to me that the only application for which the default saving option should be false is the web app.

**Comment by jdebacker** [comment] 2018-05-25 19:27
@rickecon That's right.  We just need to create a boolean parameter to handle this.  Making default such that saves files, but web app runs will have the `save_data=False`.  We just want to avoid paying more for cloud computing.

**Comment by jdebacker** [comment] 2019-04-16 00:31
Closing this issues since OG-USA is not currently being maintained on any web apps.

**Closed by jdebacker** 2019-04-16 00:31 UTC
